# Generated by Django 6.0.2 on 2026-02-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0005_season_race_raceresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-points', 'name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
    ]
